version: '3.8'

services:
    app:
        build: .
        container_name: sign_language_app
        ports:
            - "8080:8080"
        environment:
            - MODEL_PATH=${MODEL_PATH}
        volumes:
            - ./.env:/app/.env
            - ./app/sign_language_model_v4_newdata_only.keras:${MODEL_PATH}
